project_name: yaml-toolbox
release:
  github:
    owner: marrccampbell
    name: yaml-toolbox
builds:
  - id: yaml-toolbox
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
      -X github.com/marccampbell/yaml-toolbox/pkg/version.version={{.Version}}
      -X github.com/marccampbell/yaml-toolbox/pkg/version.gitSHA={{.Commit}}
      -X github.com/marccampbell/yaml-toolbox/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    binary: yaml-toolbox
    hooks: {}
archives:
  - id: yaml-toolbox
    builds:
      - yaml-toolbox
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*